name = "stoic-clone-web"
compatibility_date = "2024-05-17"

[build]
command = "pnpm build"

[[d1_databases]]
binding = "DB"
database_name = "stoic"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "./db/migrations"
